"""add vehicle owner contact fields

Revision ID: 4f4effd69a0f
Revises: 65bf7aa239f1
Create Date: 2026-08-24 08:44:44.692558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4effd69a0f'
down_revision: Union[str, Sequence[str], None] = '65bf7aa239f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('vehicles', sa.Column('owner_department', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('owner_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'owner_address')
    op.drop_column('vehicles', 'owner_department')
    op.drop_column('vehicles', 'phone_number')
    # ### end Alembic commands ###
