"""add gate checks

Revision ID: 65bf7aa239f1
Revises: 85f8493b6681
Create Date: 2026-08-24 08:12:41.668858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65bf7aa239f1'
down_revision: Union[str, Sequence[str], None] = '85f8493b6681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gate_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_checks_plate_number'), 'gate_checks', ['plate_number'], unique=False)
    op.create_index(op.f('ix_gate_checks_status'), 'gate_checks', ['status'], unique=False)
    op.create_index(op.f('ix_gate_checks_vehicle_id'), 'gate_checks', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gate_checks_vehicle_id'), table_name='gate_checks')
    op.drop_index(op.f('ix_gate_checks_status'), table_name='gate_checks')
    op.drop_index(op.f('ix_gate_checks_plate_number'), table_name='gate_checks')
    op.drop_table('gate_checks')
    # ### end Alembic commands ###
