"""create gate events

Revision ID: 85f8493b6681
Revises: cd5433b7a3be
Create Date: 2026-08-24 07:44:33.894813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f8493b6681'
down_revision: Union[str, Sequence[str], None] = 'cd5433b7a3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gate_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('detected_plate_number', sa.String(length=20), nullable=False),
    sa.Column('plate_confidence', sa.Float(), nullable=True),
    sa.Column('vehicle_confidence', sa.Float(), nullable=True),
    sa.Column('camera_id', sa.String(length=100), nullable=True),
    sa.Column('gate_id', sa.String(length=100), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decision_reason', sa.String(length=255), nullable=True),
    sa.Column('hardware_status', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_events_camera_id'), 'gate_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_gate_events_decision'), 'gate_events', ['decision'], unique=False)
    op.create_index(op.f('ix_gate_events_detected_at'), 'gate_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_gate_events_detected_plate_number'), 'gate_events', ['detected_plate_number'], unique=False)
    op.create_index(op.f('ix_gate_events_gate_id'), 'gate_events', ['gate_id'], unique=False)
    op.create_index(op.f('ix_gate_events_hardware_status'), 'gate_events', ['hardware_status'], unique=False)
    op.create_index(op.f('ix_gate_events_vehicle_id'), 'gate_events', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gate_events_vehicle_id'), table_name='gate_events')
    op.drop_index(op.f('ix_gate_events_hardware_status'), table_name='gate_events')
    op.drop_index(op.f('ix_gate_events_gate_id'), table_name='gate_events')
    op.drop_index(op.f('ix_gate_events_detected_plate_number'), table_name='gate_events')
    op.drop_index(op.f('ix_gate_events_detected_at'), table_name='gate_events')
    op.drop_index(op.f('ix_gate_events_decision'), table_name='gate_events')
    op.drop_index(op.f('ix_gate_events_camera_id'), table_name='gate_events')
    op.drop_table('gate_events')
    # ### end Alembic commands ###
