"""Create vehicles table

Revision ID: cd5433b7a3be
Revises: 
Create Date: 2026-08-24 07:07:26.395812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd5433b7a3be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('chassis_number', sa.String(length=17), nullable=False),
    sa.Column('owner_nin_number', sa.String(length=20), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_chassis_number'), 'vehicles', ['chassis_number'], unique=True)
    op.create_index(op.f('ix_vehicles_owner_nin_number'), 'vehicles', ['owner_nin_number'], unique=False)
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=False)
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_registration_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_owner_nin_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_chassis_number'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
